a = int(input("Input 1st number = "))
b = int(input("Input 2nd number = "))
print("so,", a,"+",b," = ", a+b)
print(a,"-",b," = ", a-b)
print(a,"x",b," = ", a*b)
print(a,"/",b," = ", a/b)
print(a,"^",b," = ", a**b)